GET http://localhost:3003/turma 

###

POST http://localhost:3003/turma/criar 
Content-Type: application/json

{
 "nome":"Pokemon" 
}

###

PUT http://localhost:3003/turma/editar 
Content-Type: application/json

{
    "id": "9zqohjuw",
    "modulo": "1"
}

###
POST http://localhost:3003/docente/criar 
Content-Type: application/json

{
    "nome":"kakau",
    "email": "kakau2@gmail.com",
    "dataNasc":"08/03/1985",
    "turma_id": "9zqohjuw"

}

###
GET  http://localhost:3003/docente/buscar 


###
 
PUT  http://localhost:3003/docente/mudar-de-turma 
Content-Type: application/json


{
    "id":""
    "turma_id": "9zqohjuw"
}
